openapi: "3.0.1"
info:
   title: "carbon-footprint-api"
   description: "This API provides carbon footprint of the provided offer"
   version: "1.0"

paths:

    /carbonfootprint:
        post:
            consumes:
            - "application/json"
            produces:
            - "application/json"
            responses:
                "200":
                    description: "200 response"
            security:
              - CarbonFootrpintAuthorizer: []
            x-amazon-apigateway-integration:
                httpMethod: "POST"
                credentials:
                    Fn::GetAtt: [LambdaExecutionRole, Arn]
                uri: 
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CarbonCalculator.Arn}/invocations"
                responses:
                    default:
                        statusCode: "200"
                passthroughBehavior: "when_no_match"
                type: "aws"

components:
    securitySchemes:
        CarbonFootrpintAuthorizer:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: cognito_user_pools
            x-amazon-apigateway-authorizer:
                type: cognito_user_pools
                providerARNs:
                  - Fn::GetAtt: [CarbonFootprintUserPool, Arn]