version = 0.1
[default.deploy.parameters]
stack_name = "carbon-footrpint-api"
resolve_s3 = true
s3_prefix = "carbon-footrpint-api"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
